# Generated by Django 5.2.6 on 2025-10-07 16:15

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuctionSeason',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('start_price', models.DecimalField(decimal_places=2, default=0, max_digits=18, validators=[django.core.validators.MinValueValidator(0)])),
                ('thumbnail', models.URLField(blank=True, max_length=255, null=True)),
                ('category', models.CharField(choices=[('jersey', 'Match-Worn Jersey'), ('shoes', 'Match-Worn Shoes'), ('ball', 'Match Ball'), ('artwork', 'Artwork & Posters'), ('other', 'Other')], max_length=20)),
                ('is_featured', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('active', 'Active'), ('sold', 'Sold'), ('ended', 'Ended (Not Sold)')], default='active', max_length=10)),
                ('club', models.CharField(blank=True, max_length=100, null=True)),
                ('player', models.CharField(blank=True, max_length=100, null=True)),
                ('match_date', models.DateField(blank=True, null=True)),
                ('hero_image_url', models.URLField(blank=True, help_text='Link for high-res banner image.', max_length=255, null=True)),
                ('story_details', models.TextField(blank=True, help_text='In-depth story behind the item.', null=True)),
                ('auction_season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='main.auctionseason')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to=settings.AUTH_USER_MODEL)),
                ('winner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='won_products', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bids', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bids', to='main.product')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('watchlist', models.ManyToManyField(blank=True, related_name='watched_by', to='main.product')),
            ],
        ),
    ]
