# Generated by Django 5.2.6 on 2025-09-15 14:36

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuctionSeason',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('price', models.IntegerField()),
                ('description', models.TextField()),
                ('thumbnail', models.URLField(blank=True, null=True)),
                ('category', models.CharField(choices=[('jersey', 'Match-Worn Jersey'), ('shoes', 'Match-Worn Shoes'), ('ball', 'Match Ball'), ('artwork', 'Artwork & Posters'), ('other', 'Other')], max_length=20)),
                ('is_featured', models.BooleanField(default=False)),
                ('club', models.CharField(blank=True, max_length=100, null=True)),
                ('player', models.CharField(blank=True, max_length=100, null=True)),
                ('match_date', models.DateField(blank=True, null=True)),
                ('auction_season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='main.auctionseason')),
            ],
        ),
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bids', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bids', to='main.product')),
            ],
            options={
                'ordering': ['-amount', 'created_at'],
            },
        ),
    ]
